#!/usr/bin/env bash
# ============================================================
# Rigor Project Scaffolding v1.0
#
# Usage:
#   ./scripts/init-project.sh <project-name>
#   ./scripts/init-project.sh my-url-shortener
# ============================================================
set -uo pipefail

# --- Colors ---
RED=$'\033[0;31m'
GREEN=$'\033[0;32m'
YELLOW=$'\033[1;33m'
BLUE=$'\033[0;34m'
CYAN=$'\033[0;36m'
BOLD=$'\033[1m'
NC=$'\033[0m'

log_info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC}   $1"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $1"; }

# --- Input ---
PROJECT_NAME="${1:-}"
if [ -z "$PROJECT_NAME" ]; then
    echo -e "${RED}Error: Project name required${NC}"
    echo "  Usage: init-project.sh <project-name>"
    exit 1
fi

# Convert to slug
PROJECT_SLUG=$(echo "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd 'a-z0-9-')
WORKSPACE_DIR="./workspace/$PROJECT_SLUG"

# --- Welcome ---
echo ""
echo -e "${CYAN}${BOLD}╔══════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}${BOLD}║     🚀  Rigor Project Scaffolding            ║${NC}"
echo -e "${CYAN}${BOLD}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo "  Project: ${BOLD}$PROJECT_NAME${NC} ($PROJECT_SLUG)"
echo "  Workspace: ${BOLD}$WORKSPACE_DIR${NC}"
echo ""

# --- Create Workspace ---
log_info "Creating project workspace..."
mkdir -p "$WORKSPACE_DIR"/{kanban,artifacts,reports,src,tests}

# 1. Project PRD Template (SDD Format)
log_info "Creating Product Requirements Document..."
cat > "$WORKSPACE_DIR/artifacts/prd.md" << EOF
# Project: $PROJECT_NAME

## Overview
[Describe the project goal in 1-2 sentences]

## User Stories

### Story 1: [Feature Name]
**As a** [user role]
**I want** [action]
**So that** [value]

#### Acceptance Criteria
**AC-1:**
- Given [precondition]
- When [user action]
- Then [expected result]

**AC-2:**
- Given [precondition]
- When [user action]
- Then [expected result]

### Story 2: [Feature Name]
**As a** [user role]
**I want** [action]
**So that** [value]

#### Acceptance Criteria
**AC-1:**
- Given [precondition]
- When [user action]
- Then [expected result]

## Technical Constraints
- [Constraint 1]
- [Constraint 2]

## Success Criteria
- [Criterion 1]
- [Criterion 2]
EOF
log_success "PRD template created"

# 2. Architecture Template
cat > "$WORKSPACE_DIR/artifacts/architecture.md" << EOF
# Architecture: $PROJECT_NAME

## System Design
[Describe system architecture]

## Tech Stack
- [Technology 1]
- [Technology 2]

## API Design
[API endpoints and contracts]

## Database Schema
[Tables and relationships]
EOF
log_success "Architecture template created"

# 3. Kanban Board Init
log_info "Initializing Kanban board for project..."

# Create a Kanban task template
cat > "$WORKSPACE_DIR/kanban/init-tasks.yaml" << EOF
# Initial Kanban tasks for: $PROJECT_NAME
# Load with: hermes kanban create --from-file init-tasks.yaml

tasks:
  - title: "Define project requirements and success criteria"
    description: "Product Manager: Write PRD based on user needs"
    assignee: product-manager
    priority: high

  - title: "Design system architecture"
    description: "Tech Lead: Create architecture doc with tech stack selection"
    assignee: tech-lead
    priority: high
    depends_on: [1]

  - title: "Set up project repository and CI/CD"
    description: "DevOps Engineer: Initialize repo, configure CI pipeline"
    assignee: devops-engineer
    priority: high
    depends_on: [1]

  - title: "Implement core API endpoints"
    description: "Backend Engineer: Build REST API according to architecture"
    assignee: backend-engineer
    priority: medium
    depends_on: [2]

  - title: "Write unit and integration tests"
    description: "QA Engineer: TDD-first approach, coverage > 80%"
    assignee: qa-engineer
    priority: medium
    depends_on: [4]

  - title: "Security audit"
    description: "Security Auditor: Review code for vulnerabilities"
    assignee: security-auditor
    priority: high
    depends_on: [4]
EOF
log_success "Kanban task template created"

# 4. README Template
cat > "$WORKSPACE_DIR/README.md" << EOF
# $PROJECT_NAME

> Generated by Rigor AI Engineering Team

## Quick Start
\`\`\`bash
rigor monitor          # Watch team progress
rigor kanban list      # View task status
rigor cost             # Check budget usage
\`\`\`

## Project Structure
\`\`\`
workspace/$PROJECT_SLUG/
├── artifacts/          # Design docs, PRD, architecture
├── kanban/             # Task definitions and templates
├── reports/            # QA reports, security audits
├── src/                # Source code
└── tests/              # Test files
\`\`\`
EOF
log_success "README template created"

# 5. Project Profile for Hermes (Kanban workspace)
log_info "Configuring Hermes kanban workspace..."
mkdir -p "$WORKSPACE_DIR/.hermes"
cat > "$WORKSPACE_DIR/.hermes/config.yaml" << EOF
# Rigor project config for: $PROJECT_NAME
project:
  name: "$PROJECT_NAME"
  slug: "$PROJECT_SLUG"
  kanban_board: "$WORKSPACE_DIR/kanban/board.db"
  budget_daily: 0  # Set daily budget limit (0 = unlimited)

roles:
  - orchestrator
  - product-manager
  - tech-lead
  - backend-engineer
  - frontend-engineer
  - qa-engineer
  - security-auditor
  - devops-engineer
  - technical-writer
EOF
log_success "Project config created"

# 6. .gitignore
cat > "$WORKSPACE_DIR/.gitignore" << EOF
# Rigor workspace
*.db
.pytest_cache/
__pycache__/
node_modules/
.env
*.log
EOF
log_success ".gitignore created"

# --- Summary ---
echo ""
echo -e "${GREEN}${BOLD}============================================================${NC}"
echo -e "${GREEN}${BOLD}  🎉  Project '$PROJECT_NAME' scaffolded successfully!${NC}"
echo -e "${GREEN}${BOLD}============================================================${NC}"
echo ""
echo "  📁 Workspace: $WORKSPACE_DIR/"
echo ""
echo "  Next steps:"
echo "    1. Edit ${BOLD}$WORKSPACE_DIR/artifacts/prd.md${NC}"
echo "    2. Load tasks: ${BOLD}hermes kanban create --from-file $WORKSPACE_DIR/kanban/init-tasks.yaml${NC}"
echo "    3. Watch team: ${BOLD}rigor monitor${NC}"
echo ""
