"""
SecurePaste - Backend Implementation
Generated by Rigor (AI Engineering Team)
"""
import os
import uuid
from datetime import datetime, timedelta
from typing import Optional

from fastapi import FastAPI, HTTPException, Request, Header
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import bcrypt
from cryptography.fernet import Fernet

# --- Configuration ---
AES_KEY = os.getenv("AES_KEY", Fernet.generate_key())
f = Fernet(AES_KEY)

app = FastAPI(title="SecurePaste", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- Models ---
class CreatePasteRequest(BaseModel):
    content: str
    password: Optional[str] = None
    burn_after_read: bool = False
    expiration_seconds: int = 86400  # 24h default

class CreatePasteResponse(BaseModel):
    id: str
    url: str
    expires_at: str
    burn_after_read: bool

# --- In-Memory Store (For Demo) ---
# In production, this would be a PostgreSQL database
pastes_db = {}

@app.post("/api/v1/pastes", response_model=CreatePasteResponse, status_code=201)
def create_paste(req: CreatePasteRequest):
    paste_id = str(uuid.uuid4())
    
    # 1. Encrypt content
    encrypted_content = f.encrypt(req.content.encode())
    
    # 2. Hash password if provided
    hashed_password = None
    if req.password:
        hashed_password = bcrypt.hashpw(req.password.encode(), bcrypt.gensalt()).decode()

    # 3. Store
    expires_at = datetime.utcnow() + timedelta(seconds=req.expiration_seconds)
    
    pastes_db[paste_id] = {
        "id": paste_id,
        "content": encrypted_content,
        "password_hash": hashed_password,
        "burn_after_read": req.burn_after_read,
        "expires_at": expires_at,
        "access_count": 0
    }

    return CreatePasteResponse(
        id=paste_id,
        url=f"https://securepaste.example.com/p/{paste_id}",
        expires_at=expires_at.isoformat(),
        burn_after_read=req.burn_after_read
    )

@app.get("/api/v1/pastes/{paste_id}")
def get_paste(paste_id: str, x_paste_password: Optional[str] = Header(None)):
    if paste_id not in pastes_db:
        raise HTTPException(status_code=404, detail="Paste not found")
    
    paste = pastes_db[paste_id]

    # 1. Check Expiration
    if datetime.utcnow() > paste["expires_at"]:
        del pastes_db[paste_id]
        raise HTTPException(status_code=404, detail="Paste expired")

    # 2. Check Password
    if paste["password_hash"]:
        if not x_paste_password:
            raise HTTPException(status_code=401, detail="Password required")
        if not bcrypt.checkpw(x_paste_password.encode(), paste["password_hash"].encode()):
            raise HTTPException(status_code=401, detail="Incorrect password")

    # 3. Decrypt Content
    content = f.decrypt(paste["content"]).decode()

    # 4. Burn After Read Logic (Atomic Check & Delete)
    if paste["burn_after_read"]:
        del pastes_db[paste_id]  # "Burn" it immediately

    return {"content": content}

@app.get("/health")
def health_check():
    return {"status": "ok", "active_pastes": len(pastes_db)}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
